export const YOUTUBE_PLAYLIST = {
    RESET: "YOUTUBE_PLAYLISTS_RESET",
    REQUEST: "YOUTUBE_PLAYLIST_REQUEST",
    ERROR: "YOUTUBE_PLAYLIST_ERROR",
    SUCCESS: "YOUTUBE_PLAYLIST_SUCCESS",
    SET_MODAL_OPEN: "YOUTUBE_PLAYLIST_SET_MODAL_OPEN"
};

export const YOUTUBE_PLAYLISTS = {
    RESET: "YOUTUBE_PLAYLISTS_RESET",
    REQUEST: "YOUTUBE_PLAYLISTS_REQUEST",
    ERROR: "YOUTUBE_PLAYLISTS_ERROR",
    SUCCESS: "YOUTUBE_PLAYLISTS_SUCCESS",
    ORDER_BY: "YOUTUBE_PLAYLISTS_ORDER_BY",
    SET_FILTER_STRING: "YOUTUBE_PLAYLISTS_SET_FILTER_STRING"
};

export const YOUTUBE_PLAYLIST_ITEM = {
    RESET: "YOUTUBE_PLAYLIST_ITEMS_RESET",
    REQUEST: "YOUTUBE_PLAYLIST_ITEM_REQUEST",
    ERROR: "YOUTUBE_PLAYLIST_ITEM_ERROR",
    SUCCESS: "YOUTUBE_PLAYLIST_ITEM_SUCCESS",
    SET_MODAL_OPEN: "YOUTUBE_PLAYLIST_ITEM_SET_MODAL_OPEN",
    SET_DELETE_CONFIRM_OPEN: "YOUTUBE_PLAYLIST_ITEM_SET_DELETE_CONFIRM_OPEN"
};

export const YOUTUBE_PLAYLIST_ITEMS = {
    RESET: "YOUTUBE_PLAYLIST_ITEMS_RESET",
    REQUEST: "YOUTUBE_PLAYLIST_ITEMS_REQUEST",
    ERROR: "YOUTUBE_PLAYLIST_ITEMS_ERROR",
    SUCCESS: "YOUTUBE_PLAYLIST_ITEMS_SUCCESS",
    ORDER_BY: "YOUTUBE_PLAYLIST_ITEMS_ORDER_BY",
    SET_FILTER_STRING: "YOUTUBE_PLAYLIST_ITEMS_SET_FILTER_STRING"
};

export const YOUTUBE_VIDEO = {
    RESET: "YOUTUBE_VIDEO_RESET",
    REQUEST: "YOUTUBE_VIDEO_REQUEST",
    ERROR: "YOUTUBE_VIDEO_ERROR",
    SUCCESS: "YOUTUBE_VIDEO_SUCCESS",
    RESET: "YOUTUBE_VIDEO_RESET"
};