export const YOUTUBE_PLAYLISTS = {
    RESET: "YOUTUBE_PLAYLISTS_RESET",
    REQUEST: "YOUTUBE_PLAYLISTS_REQUEST",
    ERROR: "YOUTUBE_PLAYLISTS_ERROR",
    SUCCESS: "YOUTUBE_PLAYLISTS_SUCCESS",
    ORDER_BY: "YOUTUBE_PLAYLISTS_ORDER_BY",
    SET_FILTER_STRING: "YOUTUBE_PLAYLISTS_SET_FILTER_STRING"
};