export const YOUTUBE_PLAYLISTS = {
    RESET: "YOUTUBE_PLAYLISTS_RESET",
    REQUEST: "YOUTUBE_PLAYLISTS_REQUEST",
    ERROR: "YOUTUBE_PLAYLISTS_ERROR",
    SUCCESS: "YOUTUBE_PLAYLISTS_SUCCESS"
};