export const UI_STATE = {
    INITIALIZING: "UI_STATE_INITIALIZING",
    REQUESTING: "UI_STATE_REQUESTING",
    ERROR: "UI_STATE_ERROR",
    SUCCESS: "UI_STATE_SUCCESS",
    COMPLETE: "UI_STATE_COMPLETE"
};